name: CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel

      - name: Install runtime dependencies (for tests)
        run: pip install fastapi uvicorn pydantic httpx

      # - name: Run tests # Placeholder for actual tests
      #   run: echo "No tests defined yet."

      - name: Build package
        run: python -m build

      - name: Create Release and Upload Assets
        if: startsWith(github.ref, 'refs/tags/v') # Only run if a tag starting with 'v' was pushed
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          body_path: CHANGELOG.md
          # The tag name is automatically picked from github.ref
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
